#! /usr/bin/env bash
#
#  edit and run this script to update the run scripts for the pipeline
#

common="dv=200 dw=200 restart=1 admit=0 extent=240 pix_list=1,2,3,4,6,7,8,9,10,11,12,13,14,15"



project="2021-S1-US-3"

# echo $(lmtinfo.py grep 2022 Science 2021-S1-US-3|sort|awk '{print $2}')

# good ones for the combination
on1="97520 97521 97523 97524 97528 97529 97531 97532 97861 97862 97863 97864 97868 97870 97871 97872 97873 97993 97994 97999 98000 98004 98006 98007 98011 98012"

# bad ones to be fully removed from final combination
on1b="97740 97741 97743 97744"


obsnums="$on1 $on1b"


#                       create the run file for single obsnum runs, also incoorporate any obsnum specific arguments
job1=$project.run1
job2=$project.run2
rm -f $job1 $job2
touch $job1 $job2
for o in $obsnums ; do
    if [ -e $o.args ]; then
	args=$(cat $o.args)
    fi
    echo SLpipeline.sh obsnum=$o $common $args >> $job1
    args=""
done


#                       create the run file for combination runs

echo SLpipeline.sh obsnums=$(echo $on1 | sed 's/ /,/g') srdp=1 >> $job2

echo "Found $(cat $job1 | wc -l) single obsnums in $job1"
echo "Found $(cat $job2 | wc -l) combinations in $job2"
echo "Have fun running them."
